parameters:
    # These will be overridden by DI configuration
    resque.host: ''
    resque.port: ''
    resque.password: ''
    resque.track: true

    # Can be overridden for any reason
    resque.class: "ShonM\\ResqueBundle\\Resque"
    resque.scheduler.class: "Resque\\Scheduler"

services:
    resque:
        class: %resque.class%
        arguments: [ "%resque.host%:%resque.port%", @service_container ]
        calls:
            - [setTracking, ["%resque.track%"]]
    resque.scheduler:
        class: %resque.scheduler.class%
