parameters:
    # These will be overridden by DI configuration
    resque.host: ''
    resque.port: ''
    resque.password: ''
    resque.track: true

    # Can be overridden for any reason
    resque.class: "ShonM\\ResqueBundle\\Resque"
    resque.worker_daemon.class: "ShonM\\ResqueBundle\\WorkerDaemon"
    resque.scheduler.class: "ShonM\\ResqueBundle\\ResqueScheduler"
    resque.scheduler_daemon.class: "ShonM\\ResqueBundle\\SchedulerDaemon"

services:
    resque:
        class: %resque.class%
        arguments: [ "%resque.host%:%resque.port%", @service_container, "%resque.track%" ]
    resque.worker_daemon:
        class: %resque.worker_daemon.class%
        arguments: [ "%resque.host%:%resque.port%", "%resque.password%" ]
        prototype: true
    resque.scheduler:
        class: %resque.scheduler.class%
        arguments: [ @resque ]
    resque.scheduler_daemon:
        class: %resque.scheduler_daemon.class%
        arguments: [ @resque.scheduler ]
